INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(1, '71033266097', 'Alan', 'JAMES', 5, 2, 'Banco de dados', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(2, '96446798045', 'Betty', 'SIMMONS', 5, 12, 'Banco de dados', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(3, '55798993528', 'Bobby', 'ROSS', 5, 15, 'Banco de dados', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(4, '82100280473', 'Brenda', 'FORD', 8, 15, 'Banco de dados', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(5, '90612351728', 'Catherine', 'WASHINGTON', 5, 8, 'Banco de dados', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(6, '99073972248', 'Christine', 'MCDONALD', 8, 13, 'Banco de dados', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(7, '68618995444', 'Debra', 'KENNEDY', 9, 20, 'Banco de dados', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(8, '85152587295', 'Dylan', 'WOOD', 10, 14, 'Banco de dados', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(9, '78891245316', 'Emma', 'WOODS', 9, 8, 'Banco de dados', 'Intersexo', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(10, '84097442344', 'Eugene', 'PRICE', 6, 0, 'Banco de dados', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(11, '87534302801', 'Evelyn', 'HUNTER', 4, 3, 'Banco de dados', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(12, '91291552109', 'Frances', 'SHAW', 7, 16, 'Banco de dados', 'Feminino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(13, '89003896358', 'Gabriel', 'GRAY', 10, 3, 'Banco de dados', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(14, '90937476478', 'Grace', 'MEYER', 6, 15, 'Banco de dados', 'Feminino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(15, '67592796415', 'Johnny', 'FOSTER', 5, 1, 'Banco de dados', 'Masculino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(16, '69261074960', 'Jordan', 'CHAVEZ', 6, 6, 'Banco de dados', 'Masculino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(17, '93337030792', 'Juan', 'RUIZ', 6, 4, 'Banco de dados', 'Masculino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(18, '98015855059', 'Judith', 'MENDEZ', 4, 0, 'Banco de dados', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(19, '99554681418', 'Judy', 'RICE', 10, 10, 'Banco de dados', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(20, '58824953664', 'Julia', 'FOX', 4, 15, 'Banco de dados', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(21, '81270830371', 'Karen', 'BARNES', 7, 1, 'Banco de dados', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(22, '66377269361', 'Katherine', 'HARRISON', 7, 3, 'Banco de dados', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(23, '84701642018', 'Lauren', 'GORDON', 10, 11, 'Banco de dados', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(24, '75679584507', 'Lisa', 'VASQUEZ', 9, 2, 'Banco de dados', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(25, '57129783197', 'Logan', 'ALVAREZ', 6, 4, 'Banco de dados', 'Masculino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(26, '57150917852', 'Louis', 'SANDERS', 10, 11, 'Banco de dados', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(27, '67495034437', 'Madison', 'MILLS', 10, 9, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(28, '71774966528', 'Margaret', 'FISHER', 8, 17, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(29, '91593744313', 'Marie', 'WARREN', 9, 16, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(30, '80818216300', 'Martha', 'SNYDER', 7, 8, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(31, '66825609138', 'Nancy', 'GONZALES', 6, 9, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(32, '68716425599', 'Nicole', 'MARSHALL', 10, 19, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(33, '89549710801', 'Olivia', 'SILVA', 6, 18, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(34, '82562254871', 'Pamela', 'CASTRO', 9, 3, 'Banco de dados', 'Intersexo', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(35, '82536911321', 'Philip', 'LONG', 10, 0, 'Banco de dados', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(36, '88725538553', 'Rachel', 'VARGAS', 7, 1, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(37, '89377636199', 'Ralph', 'BENNETT', 5, 12, 'Banco de dados', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(38, '86525690894', 'Randy', 'CASTILLO', 10, 0, 'Banco de dados', 'Intersexo', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(39, '68610098906', 'Roy', 'MENDOZA', 10, 9, 'Banco de dados', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(40, '80014803890', 'Russell', 'PATEL', 10, 20, 'Banco de dados', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(41, '67380702151', 'Ruth', 'OWENS', 9, 10, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(42, '90396632443', 'Samantha', 'FERNANDEZ', 10, 18, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(43, '96377476121', 'Sarah', 'HENDERSON', 5, 20, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(44, '63119744731', 'Theresa', 'SCHMIDT', 4, 9, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(45, '80113300098', 'Vincent', 'MYERS', 7, 17, 'Banco de dados', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(46, '75332205879', 'Virginia', 'WELLS', 7, 7, 'Banco de dados', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(47, '80355209504', 'Wayne', 'HUGHES', 6, 20, 'Banco de dados', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(48, '77611509140', 'Willie', 'BROOKS', 6, 8, 'Banco de dados', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(49, '55774275097', 'Abigail', 'SOTO', 5, 9, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(50, '80830562656', 'Alexander', 'CAMPBELL', 6, 13, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(51, '76852042511', 'Alexis', 'DUNN', 9, 18, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(52, '57200402542', 'Amanda', 'WALLACE', 10, 11, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(53, '97496463855', 'Amber', 'NICHOLS', 10, 13, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(54, '99843755621', 'Ana Beatriz', 'Gonçalves', 10, 9, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(55, '59249490017', 'Anthony', 'WILSON', 5, 13, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(56, '73891810505', 'Antônio', 'da Costa', 5, 16, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(57, '61441849541', 'Arthur', 'Castro', 10, 14, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(58, '97849217948', 'Ashley', 'PATTERSON', 4, 16, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(59, '71047234172', 'Beatriz', 'Pires', 4, 0, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(60, '82131935084', 'Benjamin', 'ADAMS', 6, 5, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(61, '73911690845', 'Bernardo', 'Silva', 6, 0, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(62, '61668710511', 'Bianca', 'Lopes', 4, 12, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(63, '89793773870', 'Brandon', 'FLORES', 4, 3, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(64, '79176696752', 'Brittany', 'WEAVER', 10, 19, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(65, '77075884375', 'Bruno', 'da Mata', 7, 9, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(66, '88082561631', 'Carol', 'GRIFFIN', 4, 4, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(67, '75846263960', 'Cecília', 'da Luz', 8, 20, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(68, '73794741310', 'Charles', 'MARTINEZ', 10, 19, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(69, '64281482473', 'Christopher', 'HERNANDEZ', 10, 9, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(70, '72283032018', 'Clara', 'da Paz', 9, 7, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(71, '82514349615', 'Daniel', 'LOPEZ', 6, 18, 'Ciência da Computação', 'Intersexo', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(72, '58054694485', 'Danielle', 'STEPHENS', 6, 12, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(73, '94936869901', 'Davi', 'Dias', 9, 10, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(74, '72054138041', 'Davi Lucas', 'da Rocha', 6, 4, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(75, '75310776795', 'Davi Luiz', 'da Luz', 9, 17, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(76, '74294082143', 'Deborah', 'WEST', 5, 19, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(77, '67771470327', 'Diana', 'GARDNER', 9, 7, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(78, '70143824644', 'Donald', 'ANDERSON', 4, 9, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(79, '96078264778', 'Donna', 'HAMILTON', 10, 3, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(80, '64727719347', 'Emanuel', 'da Rosa', 4, 5, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(81, '95730698265', 'Emanuelly', 'das Neves', 10, 1, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(82, '74226841493', 'Emily', 'GRAHAM', 9, 11, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(83, '86685864800', 'Enzo', 'Pereira', 4, 18, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(84, '72184788680', 'Enzo Gabriel', 'da Cunha', 6, 2, 'Ciência da Computação', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(85, '95028498771', 'Esther', 'da Conceição', 10, 20, 'Ciência da Computação', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(86, '91607324230', 'Francisco', 'da Cruz', 7, 0, 'Ciência da Computação', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(87, '85579223715', 'Frank', 'GREEN', 7, 5, 'Ciência da Computação', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(88, '55896866724', 'Gabriel', 'Cardoso', 5, 12, 'Ciência da Computação', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(89, '87802422775', 'Giovanna', 'Carvalho', 5, 19, 'Ciência da Computação', 'Feminino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(90, '92546748274', 'Gregory', 'NELSON', 8, 1, 'Ciência da Computação', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(91, '83006306304', 'Heitor', 'Oliveira', 5, 4, 'Ciência da Computação', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(92, '75011208424', 'Helena', 'Cardoso,', 8, 16, 'Ciência da Computação', 'Intersexo', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(93, '76709212705', 'Ian', 'da Paz', 8, 15, 'Ciência da Computação', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(94, '92814941309', 'João Gabriel', 'da Mota', 4, 14, 'Ciência da Computação', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(95, '81946383101', 'João Vitor', 'Vieira', 6, 17, 'Ciência da Computação', 'Masculino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(96, '90202411846', 'Justin', 'NGUYEN', 10, 20, 'Ciência da Computação', 'Masculino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(97, '61583920765', 'Kimberly', 'ALEXANDER', 8, 12, 'Ciência da Computação', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(98, '84576082462', 'Lara', 'Aragão', 5, 13, 'Ciência da Computação', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(99, '57500064385', 'Larry', 'TORRES', 7, 20, 'Ciência da Computação', 'Masculino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(100, '66520770222', 'Lavínia', 'Rodrigues', 4, 1, 'Ciência da Computação', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(101, '61231871495', 'Lori', 'KELLEY', 4, 7, 'Ciência da Computação', 'Feminino', 'Integral');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(102, '98697853336', 'Lucas', 'Souza', 9, 13, 'Ciência da Computação', 'Intersexo', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(103, '95789459920', 'Luiza', 'Mendes', 9, 7, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(104, '93220030662', 'Maria Eduarda', 'Melo', 10, 10, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(105, '97266315766', 'Maria Luiza', 'Jesus', 10, 0, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(106, '61818444647', 'Mariana', 'Viana', 10, 8, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(107, '86983369387', 'Marilyn', 'FERGUSON', 9, 6, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(108, '62425838632', 'Marina', 'da Mota', 5, 18, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(109, '90887685686', 'Mark', 'THOMAS', 8, 9, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(110, '73171353709', 'Matheus', 'Costa', 8, 8, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(111, '99478075629', 'Matthew', 'GONZALEZ', 6, 4, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(112, '75811422535', 'Melissa', 'da Rosa', 8, 16, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(113, '59992394107', 'Melissa', 'MORENO', 4, 6, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(114, '85829880750', 'Michelle', 'REYNOLDS', 5, 9, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(115, '71981991451', 'Miguel', 'Cavalcanti', 8, 5, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(116, '60302141496', 'Natalie', 'PAYNE', 6, 11, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(117, '93795650965', 'Nicole', 'Farias', 9, 16, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(118, '73232572919', 'Patrick', 'RIVERA', 7, 15, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(119, '70459266656', 'Paul', 'TAYLOR', 6, 11, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(120, '72340937537', 'Pedro', 'Campos', 9, 20, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(121, '90403549025', 'Rafael', 'Santos', 6, 18, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(122, '80925212572', 'Rafaela', 'Ramos', 10, 0, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(123, '97364081212', 'Raymond', 'HALL', 8, 14, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(124, '89804698120', 'Rebeca', 'Fernandes', 7, 1, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(125, '86941202761', 'Rebecca', 'HAYES', 4, 17, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(126, '70982644387', 'Rose', 'RYAN', 5, 17, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(127, '79667586565', 'Samuel', 'BAKER', 8, 18, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(128, '63093566834', 'Scott', 'HILL', 10, 12, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(129, '57029100687', 'Sophia', 'GRANT', 4, 9, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(130, '82487546449', 'Stephanie', 'COLE', 8, 8, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(131, '72100652952', 'Thiago', 'Nogueira', 10, 5, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(132, '76533280860', 'Thomas', 'RODRIGUEZ', 6, 20, 'Ciência da Computação', 'Masculino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(133, '63893561511', 'Valentina', 'Nunes', 10, 18, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(134, '64145893892', 'Vitória', 'Martins', 4, 0, 'Ciência da Computação', 'Feminino', 'Noturno');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(135, '63227467787', 'Aaron', 'PHILLIPS', 9, 15, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(136, '76059134116', 'Adam', 'PARKER', 9, 11, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(137, '94355846566', 'Albert', 'COX', 8, 19, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(138, '68646765054', 'Amy', 'MEDINA', 6, 8, 'Engeharia de Software', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(139, '56156691826', 'Angela', 'STEVENS', 10, 0, 'Engeharia de Software', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(140, '73823696006', 'Anna', 'MURRAY', 4, 13, 'Engeharia de Software', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(141, '84177767225', 'Austin', 'KELLY', 7, 4, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(142, '98294834305', 'Barbara', 'BELL', 10, 20, 'Engeharia de Software', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(143, '90556999713', 'Billy', 'RICHARDSON', 10, 13, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(144, '98437267044', 'Bradley', 'JIMENEZ', 8, 14, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(145, '65353394077', 'Bruce', 'WATSON', 10, 13, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(146, '81226486449', 'Bryan', 'WARD', 7, 3, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(147, '60372750744', 'Christina', 'SIMPSON', 5, 17, 'Engeharia de Software', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(148, '98610176591', 'Cynthia', 'GIBSON', 5, 2, 'Engeharia de Software', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(149, '67880375501', 'Dennis', 'CARTER', 9, 5, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(150, '59814649756', 'Diane', 'TUCKER', 7, 19, 'Engeharia de Software', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(151, '75646529999', 'Douglas', 'DIAZ', 6, 6, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(152, '61835193405', 'Elizabeth', 'SULLIVAN', 6, 20, 'Engeharia de Software', 'Feminino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(153, '62678402433', 'Eric', 'KING', 10, 3, 'Engeharia de Software', 'Masculino', 'Matutino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(154, '66289571273', 'Gary', 'YOUNG', 8, 11, 'Engeharia de Software', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(155, '83011733706', 'Heather', 'WEBB', 6, 12, 'Engeharia de Software', 'Feminino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(156, '55680472790', 'Helen', 'TRAN', 9, 13, 'Engeharia de Software', 'Feminino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(157, '83926907902', 'Henry', 'TURNER', 9, 10, 'Engeharia de Software', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(158, '57525680626', 'Jack', 'MITCHELL', 4, 16, 'Engeharia de Software', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(159, '91889704239', 'Jacob', 'WALKER', 7, 12, 'Engeharia de Software', 'Masculino', 'Vespertino');
INSERT INTO ALUNO (ID, RA, NOME, SOBRENOME, NOTA, FALTAS, CURSO, GENERO, PERIODO)VALUES(160, '81885346751', 'Jason', 'RAMIREZ', 6, 19, 'Engeharia de Software', 'Masculino', 'Vespertino');