CREATE TABLE  "ALUNO" 
   (
    "ID" NUMBER(*,0), 
	"RA" CHAR(15) NOT NULL, 
	"NOME" VARCHAR2(50) NOT NULL, 
	"SOBRENOME" VARCHAR2(50), 
	"NOTA" FLOAT(126), 
	"FALTAS" NUMBER(*,0), 
	"CURSO" VARCHAR2(50), 
	"GENERO" VARCHAR2(50), 
	"PERIODO" VARCHAR2(50), 
	 CONSTRAINT "ALUNOS_ID" PRIMARY KEY ("ID")
   ) 