DECLARE
 TYPE NOMETAB IS TABLE OF ALUNO.NOME%TYPE INDEX BY BINARY_INTEGER;
 V_NOMES NOMETAB;
BEGIN
 V_NOMES(0) := 'João';
 V_NOMES(1) := 'Maria';
 V_NOMES(2) := 'Juca';
 DBMS_OUTPUT.PUT_LINE('Nome: ' || V_NOMES(1));
END;