-- EXERCICIO 5 CALCULAR VOLUME DE OBJETOS GEOMÉTRICOS ESFERA

DECLARE
 	raio NUMBER(2):= 25;
 	volume NUMBER(5);
BEGIN
	volume:= (4/3) * 3.1415 * (raio * raio * raio);
 	DBMS_OUTPUT.PUT_LINE(volume);
END;
/