-- Captura informações de uma linha
DECLARE
	V_ALUNO ALUNO%ROWTYPE;
BEGIN
	V_ALUNO.RA := '333444555';
	SELECT NOME INTO V_ALUNO.NOME FROM ALUNO WHERE RA = V_ALUNO.RA;
	DBMS_OUTPUT.PUT_LINE ('Nome do aluno: ' || V_ALUNO.NOME);
END;