-- Verifique a situação do aluno
DECLARE
	V_NOTAS NOTAS%ROWTYPE;
	V_MEDIA NUMBER(3,2);
BEGIN
	SELECT * INTO V_NOTAS FROM NOTAS WHERE RA = '111222333';
	IF (V_NOTAS.FALTAS/V_NOTAS.AULAS > 0.25) THEN
		DBMS_OUTPUT.PUT_LINE ('REPROVADO POR FALTAS');
	ELSE
		IF (V_NOTAS.A1 >= V_NOTAS.A3) AND (V_NOTAS.A2 >= V_NOTAS.A3) THEN
			V_MEDIA := (V_NOTAS.A1+V_NOTAS.A2)/2;
		ELSIF (V_NOTAS.A2 >= V_NOTAS.A1) THEN
			V_MEDIA := (V_NOTAS.A2+V_NOTAS.A3)/2;
		ELSE
			V_MEDIA := (V_NOTAS.A1+V_NOTAS.A3)/2;
		END IF;

    	IF (V_MEDIA < 6) THEN
    		DBMS_OUTPUT.PUT_LINE ('REPROVADO POR NOTA');
    	ELSE
    		DBMS_OUTPUT.PUT_LINE ('APROVADO');
    	END IF;
	END IF;
		DBMS_OUTPUT.PUT_LINE (V_MEDIA);
END;